"""user_goal

Revision ID: 6da179a14791
Revises: 
Create Date: 2021-05-20 23:06:43.717083

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6da179a14791'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_provider', sa.Enum('GOOGLE', 'FACEBOOK', name='provider'), nullable=False),
    sa.Column('user_social_id', sa.String(), nullable=False),
    sa.Column('user_nickname', sa.String(), nullable=False),
    sa.Column('user_goal', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_nickname'),
    sa.UniqueConstraint('user_nickname'),
    sa.UniqueConstraint('user_social_id'),
    sa.UniqueConstraint('user_social_id')
    )
    op.create_table('study_rooms',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('password', sa.String(length=32), nullable=True),
    sa.Column('current_join_counts', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('study_rooms')
    op.drop_table('users')
    # ### end Alembic commands ###
